# Generated by Django 5.0.6 on 2025-12-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon_key', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('icon_key', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('ability_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('icon_key', models.CharField(max_length=30)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.hero')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.PositiveIntegerField()),
                ('ability_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ability')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveSmallIntegerField()),
                ('deaths', models.PositiveSmallIntegerField()),
                ('assists', models.PositiveSmallIntegerField()),
                ('networth', models.IntegerField()),
                ('team', models.SmallIntegerField()),
                ('is_win', models.BooleanField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='avg_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.rank'),
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('icon_key', models.CharField(max_length=30)),
                ('imbue', models.BooleanField()),
                ('type', models.CharField(choices=[('Spirit', 'Spirit'), ('Gun', 'Gun'), ('Vitality', 'Vitality')], max_length=20)),
                ('cost', models.IntegerField()),
                ('upgrades_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_from', to='tracker.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.PositiveIntegerField()),
                ('sold_time', models.PositiveIntegerField()),
                ('is_upgrade', models.BooleanField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
                ('imbued_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ability')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.match')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.shopitem')),
            ],
        ),
    ]
