# Generated by Django 5.0.6 on 2025-12-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeritem',
            name='is_upgrade',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
