# Generated by Django 5.0.6 on 2025-12-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_playeritem_is_upgrade_alter_shopitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playerability',
            name='game_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playeritem',
            name='game_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playeritem',
            name='sold_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='assists',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='deaths',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerperformance',
            name='kills',
            field=models.SmallIntegerField(),
        ),
    ]
