# Generated by Django 5.0.6 on 2025-12-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_ability_ability_id_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='icon_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='icon_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
