# Generated by Django 5.0.6 on 2025-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_ability_icon_key_alter_ability_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='type',
            field=models.CharField(choices=[('spirit', 'Spirit'), ('weapon', 'Weapon'), ('vitality', 'Vitality')], max_length=20),
        ),
    ]
